demo/urls.py
from django.urls import path

from . import views

app_name = "demo"

urlpatterns = [
    path("", views.home, name="home"),
    path("categories/", views.category),
    path("product-by-category/<slug:category>/", views.product_by_category, name="product_by_category"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
]

ecommerce_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("demo/", include("demo.urls", namespace="demo")),
]

demo/models.py
from django.db import models

# Create your models here.

demo/views.py
from django.core import serializers
from django.shortcuts import render
from inventory import models
from django.contrib.postgres.aggregates import ArrayAgg
from django.db.models import Count


def home(request):

    return render(request, "index.html")


def category(request):

    data = models.Category.objects.all()

    return render(request, "categories.html", {"data": data})


# def category(request):

#     data = models.Category.objects.all()

#     return render(request, "categories.html", {"data": data})


def product_by_category(request, category):

    # x = models.Product.objects.filter(category__name="fashion")
    # print(models.Product.objects.filter(category__name="fashion").explain(verbose=True, analyze=True))

    data = models.Product.objects.filter(category__name=category).filter(product__is_default=True).values(
        "id", "name", "slug", "created_at", "category__name", "product__store_price"
    )
    print(data)

    # data = serializers.serialize("json", x, indent=4)

    return render(request, "product_by_category.html", {"data": data})


def product_detail(request, slug):

    # x = models.Product.objects.filter(slug=slug)

    # x = models.ProductInventory.objects.filter(product__slug=slug).values("id", "product__name", "store_price", "is_default", "attribute_values__attribute_value")

    # Using chained filters approach
    # x = models.ProductInventory.objects.filter(product__slug=slug).filter(attribute_values__attribute_value="red").filter(attribute_values__attribute_value=5).select_related('product')

    # from django.db.models import Count
    # filter_arguments = [5, "red"]
    # x = models.ProductInventory.objects.filter(product__slug=slug).filter(attribute_values__attribute_value__in=filter_arguments).annotate(num_tags=Count('attribute_values')).filter(num_tags=len(filter_arguments))


    # Dynamic Filter
    filter_arguments = []

    if request.GET:
        for value in request.GET.values():
            filter_arguments.append(value)
            
        x = models.ProductInventory.objects.filter(product__slug=slug).filter(
            attribute_values__attribute_value__in=filter_arguments).annotate(
            num_tags=Count('attribute_values')).filter(num_tags=len(filter_arguments)).values(
            "id", "sku", "product__name", "store_price", "product_inventory__units").annotate(
            field_a=ArrayAgg("attribute_values__attribute_value")).get()
        print("*********************** : ",x)
    else:
        x = models.ProductInventory.objects.filter(product__slug=slug).filter(is_default=True).values(
        "id", "sku", "product__name", "store_price", "product_inventory__units").annotate(
            field_a=ArrayAgg("attribute_values__attribute_value")).get()
        print("*******else**************** : ",x)

        
    y = models.ProductInventory.objects.filter(product__slug=slug).distinct().values(
    "attribute_values__product_attribute__name", "attribute_values__attribute_value")

    z = models.ProductTypeAttribute.objects.filter(
        product_type__product_type__product__slug=slug).distinct().values(
            "product_attribute__name")

    return render(request, "product_detail.html", {"x": x, "filter": y, "z" : z})

demo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
  {% block content %}{% endblock %}
  </body>
</html>

demo/templates/categories.html
{% extends "base.html" %}
{% block title %}Categories{% endblock %}

{% block content %}
  <h1>Categories</h1>
  <ul>

  {% load cache %}
  {% cache 600 data %}
          {% for x in data %}
          <li>
          <a href="{% url 'demo:product_by_category' category=x.slug %}">{{x.name}}</a>
          </li>
      {% endfor %}
  {% endcache %}
{% endblock %}

demo/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Home</h1>
  <ul>
    <li><a href="categories/">Categories</a></li>
  </ul>
{% endblock %}

demo/templates/product_by_category.html
{% extends "base.html" %}

{% block title %}Product By Category{% endblock %}

{% block content %}
  {% comment %} <ul>
            {% for x in data %}
              <li>
              {{x.name}}
              </li>
          {% endfor %}
  </ul> {% endcomment %}

  {% comment %} <pre>{{data}}</pre> {% endcomment %}

  <ul>
    {% for x in data %}
      <li class="text-capitalize">
      {{x.name}} [<a href="{% url 'demo:product_detail' slug=x.slug %}">view</a>]
      </li>
      <ul class="list-unstyled">
      <li>{{x.id}}</li>
      <li>Price: £{{x.product__store_price}}</li>
      </ul>
    {% endfor %}
  </ul>
{% endblock %}

demo/templates/product_detail.html
{% extends "base.html" %}

{% block title %}Product Detail{% endblock %}

{% block content %}

{% comment %} 
<ul>
        {% for x in data %}
            <li>
            {% comment %} {{x.name}}
            {{x.category__name}} {% endcomment %}
            {% comment %} {{x.product__store_price}} {% endcomment %}
            {% comment %} {{x.id}} {% endcomment %}
            {% comment %} {{x.sku}} {% endcomment %}
            {% comment %} {{x.product}}
            {{x.product__name}}
            {{x.store_price}}
            {{x.is_default}}
            {{x.attribute_values__attribute_value}} {% endcomment %}
            {% comment %} </li> {% endcomment %}
        {% comment %} {% endfor %} {% endcomment %}
{% comment %} </ul>   

{% endcomment %}

<ul>
    <li class="text-capitalize">
    {{x.product__name}}
    </li>
    <ul class="list-unstyled">
    <li>SKU: {{x.sku}}
    <li>Price: £{{x.store_price}}</li>
    <li>{{x.attribute_values__attribute_value}}</li>
    <li>Stock: {{x.product_inventory__units}}</li>
    </ul>
</ul>

<ul>
  {% for y in z %}
    <li class="text-capitalize">
    {{y.product_attribute__name}}
    <ul>
      {% for a in filter %}
        {% if a.attribute_values__product_attribute__name == y.product_attribute__name  %}
        <li class="text-capitalize">
            {% if a.attribute_values__attribute_value in x.field_a %}
            <div id="target-{{a.attribute_values__attribute_value}}" class="selected fw-bold" data-attribute="{{y.product_attribute__name}}" value="{{a.attribute_values__attribute_value}}">{{a.attribute_values__attribute_value}}</div>
            {% else %}
            <div id="target-{{a.attribute_values__attribute_value}}" class="" data-attribute="{{y.product_attribute__name}}" value="{{a.attribute_values__attribute_value}}">{{a.attribute_values__attribute_value}}</div>
            {% endif %}
        </li>
        {% endif %}
      {% endfor %}
    </ul>
    </li>
  {% endfor %}
</ul>

<script>

  var d = {}

  let textBoxes = document.querySelectorAll('[id^=target]');

  let e = 0
  let f = textBoxes.length

  for (let i in textBoxes) {
    if (e < f) {
      if (textBoxes[i].classList.contains("selected")) {
          d[textBoxes[i].getAttribute('data-attribute')] = textBoxes[i].getAttribute('value')
      }
    } else {
      break
    }
    e++
    console.log(d)
  }

  document.addEventListener('click', function(e) {
  let value = e.target.getAttribute('value');
  d[e.target.getAttribute('data-attribute')] = e.target.getAttribute('value')
  let querystring = buildUrlWithParams(d)
  let url = window.location.href.split('?')[0]
  window.location.href = url + "?" + querystring;
  }, false);

  {% comment %} $('[id^=target]').click(function () {
    const value = this.getAttribute('value');
    d[this.getAttribute('data-attribute')] = this.getAttribute('value')
    const querystring = buildUrlWithParams(d)
    const url = window.location.href.split('?')[0]
    window.location.href = url + "?" + querystring;
  }); {% endcomment %}

  function buildUrlWithParams(data) {
    var searchparams = [];
    for (var d in data)
      searchparams.push(d + '=' + data[d]);
    return searchparams.join('&');
  }

</script>

{% endblock %}